<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Zivotinja extends \App\Models\Entities\Zivotinja implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'idZivotinja', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'latinskiNaziv', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'naslovnaSlika', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'atrakcija', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'idPredeo', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'slike'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'idZivotinja', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'latinskiNaziv', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'naslovnaSlika', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'atrakcija', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'idPredeo', '' . "\0" . 'App\\Models\\Entities\\Zivotinja' . "\0" . 'slike'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Zivotinja $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdZivotinja()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdZivotinja();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdZivotinja', []);

        return parent::getIdZivotinja();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaziv($naziv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaziv', [$naziv]);

        return parent::setNaziv($naziv);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaziv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaziv', []);

        return parent::getNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatinskiNaziv($latinskiNaziv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatinskiNaziv', [$latinskiNaziv]);

        return parent::setLatinskiNaziv($latinskiNaziv);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatinskiNaziv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatinskiNaziv', []);

        return parent::getLatinskiNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaslovnaSlika($naslovnaSlika)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaslovnaSlika', [$naslovnaSlika]);

        return parent::setNaslovnaSlika($naslovnaSlika);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaslovnaSlika()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaslovnaSlika', []);

        return parent::getNaslovnaSlika();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtrakcija($atrakcija)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtrakcija', [$atrakcija]);

        return parent::setAtrakcija($atrakcija);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtrakcija()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtrakcija', []);

        return parent::getAtrakcija();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPredeo(\App\Models\Entities\Predeo $idPredeo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPredeo', [$idPredeo]);

        return parent::setIdPredeo($idPredeo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPredeo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPredeo', []);

        return parent::getIdPredeo();
    }

    /**
     * {@inheritDoc}
     */
    public function addSlike(\App\Models\Entities\Slika $slike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSlike', [$slike]);

        return parent::addSlike($slike);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSlike(\App\Models\Entities\Slika $slike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSlike', [$slike]);

        return parent::removeSlike($slike);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlike()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlike', []);

        return parent::getSlike();
    }

}
