<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Zahtev extends \App\Models\Entities\Zahtev implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'idZahtev', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'nazivPredela', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'opisPredela', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'nazivZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'latNazivZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'opisZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'slikaPredela', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'slikaZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'komentar', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'status', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'idUser', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'tipZahteva'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'idZahtev', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'nazivPredela', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'opisPredela', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'nazivZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'latNazivZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'opisZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'slikaPredela', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'slikaZivotinje', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'komentar', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'status', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'idUser', '' . "\0" . 'App\\Models\\Entities\\Zahtev' . "\0" . 'tipZahteva'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Zahtev $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdZahtev()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdZahtev();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdZahtev', []);

        return parent::getIdZahtev();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazivPredela($nazivPredela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazivPredela', [$nazivPredela]);

        return parent::setNazivPredela($nazivPredela);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazivPredela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazivPredela', []);

        return parent::getNazivPredela();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpisPredela($opisPredela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpisPredela', [$opisPredela]);

        return parent::setOpisPredela($opisPredela);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpisPredela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpisPredela', []);

        return parent::getOpisPredela();
    }

    /**
     * {@inheritDoc}
     */
    public function setNazivZivotinje($nazivZivotinje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNazivZivotinje', [$nazivZivotinje]);

        return parent::setNazivZivotinje($nazivZivotinje);
    }

    /**
     * {@inheritDoc}
     */
    public function getNazivZivotinje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNazivZivotinje', []);

        return parent::getNazivZivotinje();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatNazivZivotinje($latNazivZivotinje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatNazivZivotinje', [$latNazivZivotinje]);

        return parent::setLatNazivZivotinje($latNazivZivotinje);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatNazivZivotinje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatNazivZivotinje', []);

        return parent::getLatNazivZivotinje();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpisZivotinje($opisZivotinje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpisZivotinje', [$opisZivotinje]);

        return parent::setOpisZivotinje($opisZivotinje);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpisZivotinje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpisZivotinje', []);

        return parent::getOpisZivotinje();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlikaPredela($slikaPredela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlikaPredela', [$slikaPredela]);

        return parent::setSlikaPredela($slikaPredela);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlikaPredela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlikaPredela', []);

        return parent::getSlikaPredela();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlikaZivotinje($slikaZivotinje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlikaZivotinje', [$slikaZivotinje]);

        return parent::setSlikaZivotinje($slikaZivotinje);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlikaZivotinje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlikaZivotinje', []);

        return parent::getSlikaZivotinje();
    }

    /**
     * {@inheritDoc}
     */
    public function setKomentar($komentar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKomentar', [$komentar]);

        return parent::setKomentar($komentar);
    }

    /**
     * {@inheritDoc}
     */
    public function getKomentar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKomentar', []);

        return parent::getKomentar();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(\App\Models\Entities\Korisnik $idUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipZahteva(\App\Models\Entities\Tip $tipZahteva = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipZahteva', [$tipZahteva]);

        return parent::setTipZahteva($tipZahteva);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipZahteva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipZahteva', []);

        return parent::getTipZahteva();
    }

}
