<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Predeo extends \App\Models\Entities\Predeo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'idPredeo', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'opisPredela', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'slika', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'zivotinje'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'idPredeo', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'opisPredela', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'slika', '' . "\0" . 'App\\Models\\Entities\\Predeo' . "\0" . 'zivotinje'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Predeo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPredeo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdPredeo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPredeo', []);

        return parent::getIdPredeo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaziv($naziv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaziv', [$naziv]);

        return parent::setNaziv($naziv);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaziv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaziv', []);

        return parent::getNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpisPredela($opisPredela)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpisPredela', [$opisPredela]);

        return parent::setOpisPredela($opisPredela);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpisPredela()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpisPredela', []);

        return parent::getOpisPredela();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlika($slika)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlika', [$slika]);

        return parent::setSlika($slika);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlika()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlika', []);

        return parent::getSlika();
    }

    /**
     * {@inheritDoc}
     */
    public function addZivotinje(\App\Models\Entities\Zivotinja $zivotinje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addZivotinje', [$zivotinje]);

        return parent::addZivotinje($zivotinje);
    }

    /**
     * {@inheritDoc}
     */
    public function removeZivotinje(\App\Models\Entities\Zivotinja $zivotinje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeZivotinje', [$zivotinje]);

        return parent::removeZivotinje($zivotinje);
    }

    /**
     * {@inheritDoc}
     */
    public function getZivotinje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZivotinje', []);

        return parent::getZivotinje();
    }

}
