<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lajkovi extends \App\Models\Entities\Lajkovi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'idLajk', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'flag', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'idUser', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'idSlika'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'idLajk', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'flag', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'idUser', '' . "\0" . 'App\\Models\\Entities\\Lajkovi' . "\0" . 'idSlika'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lajkovi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdLajk()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLajk();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLajk', []);

        return parent::getIdLajk();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlag($flag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlag', [$flag]);

        return parent::setFlag($flag);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlag', []);

        return parent::getFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(\App\Models\Entities\Korisnik $idUser = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSlika(\App\Models\Entities\Slika $idSlika = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSlika', [$idSlika]);

        return parent::setIdSlika($idSlika);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSlika()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSlika', []);

        return parent::getIdSlika();
    }

}
